<?php

namespace Jtrw\DAO\Tests\Src;

use Jtrw\DAO\DataAccessObjectInterface;
use Jtrw\DAO\Exceptions\DatabaseException;
use Jtrw\DAO\Tests\ClickHouseConnector;
use Jtrw\DAO\ValueObject\ValueObjectInterface;
use PHPUnit\Framework\Assert;
use PHPUnit\Framework\TestCase;

class ClickHouseObjectTest extends TestCase
{
    public const TABLE_TEST = "test";
    
    public DataAccessObjectInterface $db;
    
    public function setUp(): void
    {
        $this->db = ClickHouseConnector::getInstance();
        parent::setUp(); // TODO: Change the autogenerated stub
    }
    
    public function testGetDataBaseType()
    {
        Assert::assertEquals(ClickHouseConnector::DRIVER_NAME, $this->db->getDatabaseType());
    }
    
    public function testInsert()
    {
        $id = random_int(0, 10000);
        $values = [
            'id' => $id,
        ];
        
        $this->db->insert(static::TABLE_TEST, $values);
        
        $sql = "SELECT * FROM ".static::TABLE_TEST;
        $search = [
            'id' => $id
        ];
        $result = $this->db->select($sql, $search, [], DataAccessObjectInterface::FETCH_ROW);
        Assert::assertInstanceOf(ValueObjectInterface::class, $result);
        
        $resultData = $result->toNative();
        Assert::assertNotEmpty($resultData);
        Assert::assertEquals($values['id'], $resultData['id']);
    }
    
    public function testDelete()
    {
        $idSetting = 2222;
        
        $values = [
            'id' => 2222,
        ];
        
        $this->db->insert(static::TABLE_TEST, $values);
        Assert::assertIsInt($idSetting);

        $this->removeSettingRow($idSetting);

        $search = [
            'id' => $idSetting
        ];

        $sql = "SELECT * FROM ".static::TABLE_TEST;

        $result = $this->db->select($sql, $search, [], DataAccessObjectInterface::FETCH_ROW);

        Assert::assertEmpty($result->toNative());
    }
    
    private function removeSettingRow(int $id): void
    {
        $this->db->delete(static::TABLE_TEST, ['id' => $id]);
    }
    
    public function testDeleteTable()
    {
        $tableName = "test_".time();
        $sql = "CREATE TABLE {$tableName} (id UInt64) ENGINE = MergeTree ORDER BY id;";
        $this->db->query($sql);

        $sqlSelect = "SELECT * FROM ".$tableName;

        $result = $this->db->select($sqlSelect)->toNative();
        Assert::assertEmpty($result);

        $this->db->deleteTable($tableName);

        try {
            $this->db->select($sqlSelect)->toNative();
            Assert::fail('DatabaseException was not thrown');
        } catch (\ClickHouseDB\Exception\DatabaseException $exp) {
            $msg = sprintf("Table default.%s doesn't exist.", $tableName);
            Assert::assertEquals($exp->getCode(), 60);
            Assert::assertStringContainsString($msg, $exp->getMessage(), "Message Not Found");
        }
    }
    
    public function testGetTables()
    {
        Assert::assertSame(
            $this->db->getTables(),
            [
                static::TABLE_TEST,
            ]
        );
    }
    
    public function testAssoc()
    {
        $sql = "SELECT id FROM ".static::TABLE_TEST;

        $fetchAssocObject = $this->db->select($sql, [], [], DataAccessObjectInterface::FETCH_ASSOC);
        Assert::assertInstanceOf(ValueObjectInterface::class, $fetchAssocObject);

        $fetchAllObject = $this->db->select($sql, [], [], DataAccessObjectInterface::FETCH_ALL);
        Assert::assertInstanceOf(ValueObjectInterface::class, $fetchAllObject);

        $assocData = $fetchAssocObject->toNative();
        $allData = $fetchAllObject->toNative();
        Assert::assertNotEmpty($allData[0]);

        Assert::assertEquals($assocData[$allData[0]['id']]['id'], $allData[0]['id']);
    }
    
    public function testMassInsert()
    {
        $idOne = random_int(0, 5000);
        $idTwo = random_int(0, 5000);
        $values = [
            [
                'id' => $idOne,
            ],
            [
                'id' => $idTwo,
            ]

        ];
        $this->db->massInsert(static::TABLE_TEST, $values);

        $sql = "SELECT * FROM ".static::TABLE_TEST;
        $search = [
            'id' => $values[1]['id']
        ];
        $result = $this->db->select($sql, $search, [], DataAccessObjectInterface::FETCH_ROW);
        Assert::assertInstanceOf(ValueObjectInterface::class, $result);

        $resultData = $result->toNative();
        Assert::assertNotEmpty($resultData);
        Assert::assertEquals($values[1]['id'], $resultData['id']);
    }
    
    /**
     * Test UPDATE mutation in ClickHouse.
     * Note: ClickHouse mutations are asynchronous, so we only verify the query executes.
     */
    public function testUpdate()
    {
        $id = random_int(100000, 200000);
        $values = [
            'id' => $id,
        ];

        $this->db->insert(static::TABLE_TEST, $values);

        // Execute UPDATE mutation
        $updateValues = [
            'id' => $id + 1
        ];

        $search = [
            'id' => $id
        ];

        $result = $this->db->update(static::TABLE_TEST, $updateValues, $search);
        Assert::assertIsInt($result);
    }

    /**
     * Test getTableIndexes returns array with table info and data skipping indexes.
     */
    public function testGetTableIndexes()
    {
        $indexes = $this->db->getTableIndexes(static::TABLE_TEST);

        Assert::assertIsArray($indexes);
        Assert::assertArrayHasKey('table_info', $indexes);
        Assert::assertArrayHasKey('data_skipping_indexes', $indexes);
    }

    /**
     * Test setForeignKeyChecks does not throw an exception.
     * ClickHouse doesn't support foreign keys, but method should work for interface compatibility.
     */
    public function testSetForeignKeyChecks()
    {
        // Should not throw exception
        $this->db->setForeignKeyChecks(true);
        $this->db->setForeignKeyChecks(false);
        Assert::assertTrue(true);
    }

    /**
     * Test getInsertID returns 0 for ClickHouse.
     * ClickHouse doesn't support auto-increment IDs.
     */
    public function testGetInsertID()
    {
        $id = random_int(200000, 300000);
        $values = [
            'id' => $id,
        ];

        $this->db->insert(static::TABLE_TEST, $values);

        // ClickHouse doesn't support auto-increment, should return 0
        $insertId = $this->db->getInsertID();
        Assert::assertEquals(0, $insertId);
    }

    /**
     * Test transaction methods don't throw exceptions.
     * ClickHouse doesn't support traditional ACID transactions,
     * but methods should work for interface compatibility.
     */
    public function testTransactions()
    {
        // Should not throw exceptions
        $this->db->begin();

        $id = random_int(300000, 400000);
        $values = [
            'id' => $id,
        ];
        $this->db->insert(static::TABLE_TEST, $values);

        $this->db->commit();

        // Test rollback also doesn't throw
        $this->db->begin();
        $this->db->rollback();

        Assert::assertTrue(true);
    }

    /**
     * Test inTransaction returns false for ClickHouse.
     * ClickHouse doesn't support traditional transactions.
     */
    public function testInTransaction()
    {
        Assert::assertFalse($this->db->inTransaction());

        $this->db->begin();
        // Even after begin, should be false (ClickHouse doesn't really track this)
        Assert::assertFalse($this->db->inTransaction());

        $this->db->commit();
    }
}
